//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public string SID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
