//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string SID { get; set; }
        public System.DateTime Clock_In { get; set; }
        public Nullable<System.DateTime> Clock_Out { get; set; }
        public string ID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
