//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public string CID { get; set; }
        public string CourseName { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public string Description { get; set; }
        public string FID { get; set; }
    
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
