//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string FID { get; set; }
        public string Password { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
